"""Shared styling values for the PDF export."""

from datetime import datetime

ACCENT = "#1F4E79"  # dark navy — headings, table header background, heading rules
DISCLAIMER = "#B00020"  # muted red — the AI-generated disclaimer line
BODY = "#1A1A1A"
MUTED = "#444444"
RULE = "#CCCCCC"
CODE_BG = "#F2F2F2"

# ReportLab's built-in Type 1 fonts, always present with the library itself —
# no font files to install and no system font lookup, which is what makes the
# PDF render identically wherever the skill runs.
BODY_FONT = "Helvetica"
BODY_FONT_BOLD = "Helvetica-Bold"
CODE_FONT = "Courier"

DISCLAIMER_TEXT = "Generated by AI — review before use."


def format_generated_date(dt: datetime) -> str:
    return dt.strftime("%B %d, %Y")
